### ISSUE TITLE
[📑 Docs]: Update Readme to be consistent with another repos

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/converter-js#108]
### What Dev Docs changes are you proposing?

- [ ] add banner like in another repos with AsyncAPI logo
- [ ] add `all-contributors` section
- [ ] add TOC
- [ ] add development/contributing section  

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by magicmatatjahu** [comment]
@mcturco As I see we forgot to create issue for new banner with new design for that repo. Similar situation is in https://github.com/asyncapi/markdown-template

**Comment by mcturco** [comment]
@magicmatatjahu Yes, for now I didn't make issues for the repos that weren't using an old AsyncAPI logo. I figured once we get all the other ones updated then we can move on to these other repos! But for sure I can make a banner for this one 😄
