### ISSUE TITLE
Support converting to 3.0.0

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/converter-js#110]
It's a long term feature request. 

When we will have the `3.0.0` specification stabilized we should start writing functionality for converting versions `2.X.X` to `3.0.0`.

One of the problems I see are the external sources (local files and http links) which we are not converting at the moment but we should (see issue https://github.com/asyncapi/converter-js/issues/90). In order not to cause problems for people and increase DX we should figure out a way to convert also external files in which messages (and other reusable components) can be defined.

### Scope
- [x] #188
- [ ] https://github.com/asyncapi/converter-js/issues/90
- [x] https://github.com/asyncapi/converter-js/issues/106
- [x] https://github.com/asyncapi/converter-js/issues/107

**Comment by jonaslagoni** [comment]
> handle reusable parts - #90

I will leave out this feature, for now, and introduce it later after v3.
