### ISSUE TITLE
Converter ignores migration of component/parameters

### ISSUE THREAD

**Issue by aerfio** [asyncapi/converter-js#2]
Pipe https://github.com/asyncapi/asyncapi/blob/master/examples/1.2.0/streetlights.yml to converter and then to parser-js, and see such an error:

![image](https://user-images.githubusercontent.com/17271979/64781017-26719500-d562-11e9-86d4-ecb19c41aea8.png)

Converter does not delete "name" field of components/parameters, which leads to such kind of problem

**Comment by fmvilas** [comment]
Thanks for reporting, @aerfio. Will work on it as soon as I have time.
