### ISSUE TITLE
Remove messageId from v3 conversion

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/converter-js#201]
#### Reason/Context

As messageId now will be removed, we need to also remove it from the conversion to v3.

This can be achieved by altering the `convertMessages` function to now more generically also remove messageId along side the schema union changes: https://github.com/asyncapi/converter-js/blob/4571928b9e27357af1548787ace914cf8b62f7fe/src/third-version.ts#L327

Feel free to reach out if you have any questions

Related spec issue: https://github.com/asyncapi/spec/issues/978

**Comment by devilkiller-ag** [comment]
Hi, Can I work on this issue?

**Comment by jonaslagoni** [comment]
Fixed by https://github.com/asyncapi/converter-js/pull/202.

Sorry @devilkiller-ag, maybe this peak your interest https://github.com/asyncapi/converter-js/issues/195?

Feel free to ask follow up questions and ask for more specific descriptions on the issue 🙂
