### ISSUE TITLE
Convert OpenAPI 3.0 to AsyncAPI 3.0

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/converter-js#233]
This issue is part of a longer vision for the converter that can be found here: https://github.com/asyncapi/converter-js/issues/221

It would be great to open up how easily people can switch or try out AsyncAPI based on existing resources. One of these is OpenAPI 3.0: https://spec.openapis.org/oas/v3.0.3. With the new AsyncAPI v3, we should be able to map this 100% from OpenAPI to AsyncAPI.

**In order to solve this it requires a lot of conversion that might not be straightforward. While this issue is tagged as a `good first issue` it requires a lot of effort to push through, on the bright side, solving this issue will help you gain knowledge about OpenAPI and AsyncAPI, and how they relate and differentiate. Of course alongside a huge deal of TS, testing, documentation, and working in Open Source in general.**

To make it easier to digest, this issue can be split up into multiple sections to simplify the process of solving this:

1. Step: Convert the following OpenAPI keywords to form a basic AsyncAPI document with no channels nor operations: `openapi`, `info`, `servers`, `tags`, `externalDocs`, and `security`.
2. Step: Convert the OpenAPI [`paths` keyword](https://spec.openapis.org/oas/v3.0.3#paths-object) into channels and operations in AsyncAPI
3. Step: Convert the [OpenAPI components](https://spec.openapis.org/oas/v3.0.3#components-object) into AsyncAPI components

**Potential next steps that should NOT be focused on right now**

4. Step: Enable multiple options to customize the conversion.
5. Step: Enable the split of the OpenAPI document into one or more AsyncAPI documents.
6. Step: Integrate it into the AsyncAPI CLI to enable faster conversions for users.
7. Write a blog post about this new conversion

> NOTICE, because of the difficulty of this issue, you will be able to contact me all the time through Slack if you get stuck solving it at any point and even have calls when relevant.

**Comment by aeworxet** [comment]
### Bounty Issue's service comment

Text labels: `bounty/2024-Q2`, `bounty/advanced`, `bounty/coding`
First assignment to third-party contributors: [2024-03-22 00:00:00 UTC+12:00](https://time.lol/#2024-03-22T00:00:00+12:00)
End Of Life: [2024-08-31 23:59:59 UTC-12:00](https://time.lol/#2024-08-31T23:59:59-12:00)

@asyncapi/bounty_team

**Comment by AayushSaini101** [comment]
@jonaslagoni I am interested in this issue, can you assign to me? Proof of https://github.com/asyncapi/generator/pull/1061 of previous bounty issue

**Comment by aeworxet** [comment]
@AayushSaini101, taking into account the [commit history of PR asyncapi/generator#1061](https://github.com/asyncapi/generator/pull/1061/commits) (your own changes are simple and a lot of coding help is provided by @derberg,) I would propose you to concentrate on only one Bounty Issue of Complexity Level `Medium` for now, to avoid the risk of misperformance on both Bounty Issues simultaneously and the possibility of receiving an eight-month Suspension for this.

**Comment by AayushSaini101** [comment]
> @AayushSaini101, taking into account the [commit history of PR asyncapi/generator#1061](https://github.com/asyncapi/generator/pull/1061/commits) (your own changes are simple and a lot of coding help is provided by @derberg,) I would propose you to concentrate on only one Bounty Issue of Complexity Level `Medium` for now, to avoid the risk of misperformance on both Bounty Issues simultaneously and the possibility of receiving an eight-month Suspension for this.
Thanks @aeworxet

**Comment by alaminthespecial** [comment]
Hi, @jonaslagoni can you assign this issue to me.

**Comment by jonaslagoni** [comment]
@alaminthespecial quick question, how will you approach the task, beside what I already wrote in the issue? 🙂

**Comment by alaminthespecial** [comment]
@jonaslagoni

-  I would study the documentation OpenApi and  AsyncApi document and the similarity between them in which format of documents they generate.
- I will explore the converter repo more again any existing repo 
- I would start coding your first step which is a conversion of openapi to asyncapi document without operation
- i would write a input (openapi) and output(expected asyncapi) test write code similar to the conversion of versions but in this case is for the key.

**Comment by jonaslagoni** [comment]
@alaminthespecial based on [your previous contributions](https://github.com/search?alaminthespecial=&q=is%3Apr+author%3Aalaminthespecial&type=pullrequests) and your described approach I don't think it's something you can achieve in the bounty window.

It sounds like there is too much groundwork that needs to be laid before you get to solving the problem at hand 🙂

**Comment by alaminthespecial** [comment]
Thank you @jonaslagoni but I believe in learning by doing and In my previous contribution I was new to open source could you give me a try .

**Comment by jonaslagoni** [comment]
@alaminthespecial nothing is stopping you from contributing this, but it will not be as part of the selected bounty program 🙂

**Comment by aeworxet** [comment]
@jonaslagoni

I would take https://github.com/asyncapi/converter-js/blob/master/src/third-version.ts and use it as a blueprint for writing conversion of OpenAPI 3.0.0 to AsyncAPI 3.0.0, because the beginnings of [OpenAPI 3.0.0 Object](https://spec.openapis.org/oas/v3.0.3#openapi-object) and [AsyncAPI 2.6.0 Object](https://v2.asyncapi.com/docs/reference/specification/v2.6.0#A2SObject) are very close.

The only thing is that
```ts
if (fromVersion === toVersion) {
  throw new Error(`Cannot convert to the same version.`);
}
```
in https://github.com/asyncapi/converter-js/blob/master/src/convert.ts#L36 immediately starts being an issue because we ARE converting from version 3.0.0 to version 3.0.0, so either additional condition is required or a new `convert` function.

Here is a first draft of what I would do.
https://github.com/asyncapi/converter-js/commit/1130edfd2727c042e4835d746c6fba4ae9da88b1

In general, do you find this approach suitable?

**Comment by labibshadik** [comment]
Hello @jonaslagoni, I want to work on this issue.

**Comment by axif0** [comment]
hello @jonaslagoni, i want to work on this issue.

**Comment by jonaslagoni** [comment]
@axif0 as part of the bounty program or regular contribution? 

As this issue is harder than regular `good-first-issues`, I always start by asking how you would approach this issue, to check how much context you have 🙂

**Comment by Gmin2** [comment]
Hey @jonaslagoni i would like to attempt this 

I have prepared an outline for the first objective

> Step: Convert the following OpenAPI keywords to form a basic AsyncAPI document with no channels nor operations: `openapi`, `info`, `servers`, `tags`, `externalDocs`, and `security`.

As. openApi 3.0.0 is mostly similar with asyncapi 2.6.0 version i have thought the solution to convert(or use) openAPI to asyncapi 2.6.0 first.

- The `asyncapi` version string is similar to `openapi` we just have to rename it.
-  The `info`object is similar to asyncapi(2.6.0) `info` we just have to rename it.
we can use something like this :)(skip some types here)
```js
interface OpenAPIInfo {
  title: string;
  description?: string;
  termsOfService?: string;
  contact?: OpenAPIContact;
  license?: OpenAPILicense;
  version: string;
}
interface AsyncAPIInfo {
  title: string;
  description?: string;
  termsOfService?: string;
  contact?: AsyncAPIContact;
  license?: AsyncAPILicense;
  version: string;
}

function convertInfo(info: OpenAPIInfo): AsyncAPIInfo {
  return {
    title: info.title,
    description: info.description,
    termsOfService: info.termsOfService,
    contact: info.contact,
    license: info.license,
    version: info.version,
  };
}
```
- for the `server` object part 
we can extract `url` from the `protocol:\\`+`url\`+`protocolVersion` of the openAPI as openAPI's url eg(https://development.gigantic-server.com/v1),i have thought of giving a default `protocolversion` to each `protocol`(i dont have found anything apart from [this](https://stackoverflow.com/questions/77363357/api-endpoints-with-protocol-version) regarding the protocolVersion in openAPi),`description` and `variables` remain same .

- `security` can be extracted from the `server object` of asyncAPI 2.6.0
- `tags` remains the same  from 3.0.0
-  `externalDocs` remains the same from 3.0.0

**Comment by jonaslagoni** [comment]
@Gmin2 it will be impossible to convert OpenAPI to AsyncAPI v2 as they are simply not compatible when it comes to operations, channels, and reply is not even an option.

You are completely right on first step though.

How will you achieve the last two?
> Step 2: Convert the OpenAPI [paths keyword](https://spec.openapis.org/oas/v3.0.3#paths-object) into channels and operations in AsyncAPI
> Step 3: Convert the [OpenAPI components](https://spec.openapis.org/oas/v3.0.3#components-object) into AsyncAPI components

**Comment by Gmin2** [comment]
> @Gmin2 it will be impossible to convert OpenAPI to AsyncAPI v2 as they are simply not compatible when it comes to operations, channels, and reply is not even an option.

i was saying that as the step 1 mentioned keywoards(openAPI 3.0) and asyncapi 2.6.0 are pretty similar we can reuse many of the functions of [third-version.ts](https://github.com/asyncapi/converter-js/blob/master/src/third-version.ts).

> Step 2: Convert the OpenAPI [paths keyword](https://spec.openapis.org/oas/v3.0.3#paths-object) into channels and operations in AsyncAPI

For this step the brief outline is

- /{path} will be from channels object `address`
- `summary`,`description` will come from the channel summary and description
- if  method is `get` then in the operation object `action` will be`recieve` and if the method is put,patch,delete the operation object action will be sent
The operation object of the `get` method
-  `channelsName` like here
-

**Comment by Gmin2** [comment]
> @Gmin2 it will be impossible to convert OpenAPI to AsyncAPI v2 as they are simply not compatible when it comes to operations, channels, and reply is not even an option.

i was saying that as the step 1 mentioned keywoards(openAPI 3.0) and asyncapi 2.6.0 are pretty similar we can reuse many of the functions of [third-version.ts](https://github.com/asyncapi/converter-js/blob/master/src/third-version.ts).

for converting the openAPI path keywoards, i have thought of doing something like this

For this step the brief outline is

- For each channel in the AsyncAPI document, create a corresponding `path `in the OpenAPI document, /{path} will be from channels object address, create a `path Item Object` for each path
- For each operation defined in the AsyncAPI document, create a corresponding `operation` in the OpenAPI `path Item Object`
- if  method is `get`,`put`, `delete` then in the operation object action will be`recieve` and if the method is `put`, operation object action will be sent
- `summary`,`description` will come from the `channel` summary and description.

For handling request and response bodies
- Iterate through the `messages` field of the AsyncAPI `operation`.
- For each message:
    - If it corresponds to a request message, map ior bindings and trats headers and payload to the requestBody field of the OpenAPI operation.
    - If it corresponds to a response message, map its headers and payload to the responses field of the OpenAPI operation.
    
For handling parameters
- If the AsyncAPI `channel` has `parameters`, convert it to OpenAPI `parameter objects` and add them to the `path item object`

i am working on the conversion of the component part,

**Comment by jonaslagoni** [comment]
@Gmin2 please ready through your proposal again and compare it with what is being asked 😅 You are reversing stuff

**Comment by Gmin2** [comment]
lol

**Comment by Gmin2** [comment]
- creating channels 
     - for each `path` in openAPi document , create a corresponding `channel` in the 
     - 
     - AsyncAPI document, the channels `address` keywoard should be extracted from the `path` string of openAPI.
-  creating `operations`
    - for each operation in openAPI file(get,put,post,delete), create a corresponding `operation` in AsyncAPI document
    - for `post` operations, set `actions` to `send`, and for the rest set it to `recieve`.
    - set the `channel` field to a reference object pointing in the corresponding asyncapi `channel`(eg: ''$ref": "#channels/{channelAddress}"), channelAddress here is the address of the channel created/mapped from openAPI `path`
    - map the `title`,`summary`,`description` fields from openAPI path.
- `messages` field can be handled based on the `requestBody` and `responses` 
    - if openAPi has a `requestBody`, create a new message defination in the `components.message` section, message defination will contain `headers` and `payload`, `headers` will be mapped from openAPI `requestBody` to the AsyncAPI message headers,`payload` will be mapped from the schema or content from the openAPI `requestBody` to the asyncapi message payload.
    - add a reference to this message defination in the `messages` field of the asyncapi
 -

**Comment by jonaslagoni** [comment]
> for post operations, set actions to send, and for the rest set it to recieve.

This is wrong, it will only be receive, if it's from the server's perspective that we generate the AsyncAPI document to document the server as the application. 

It will be send for a client application.

This is the tough problem to solve for this entire task :v: Might need an option to determine which application you generate for :slightly_smiling_face: 

@Gmin2 sounds like you are on the right track :muscle: Let me know how I can help, and are you looking to solve this under the bounty program or just as a regular contribution?

**Comment by Gmin2** [comment]
> are you looking to solve this under the bounty program or just as a regular contribution?
 
 i would like to solve it under the bounty program 
 cc @aeworxet

**Comment by aeworxet** [comment]
### Bounty Issue's Timeline
|Complexity Level|Assignment date (by GitHub)|Start date (by BP rules)|End date (by BP rules)|Draft PR submission|Final PR submission|Final PR merge|
|----------------|---------------------------|------------------------|----------------------|-------------------|-------------------|--------------|
|Advanced        |2024-05-21                 |[2024-05-27](https://time.lol/#2024-05-27T00:00:00+12:00)              |**[2024-07-19](https://time.lol/#2024-07-19T23:59:59-12:00)**        |[2024-06-14](https://time.lol/#2024-06-14T23:59:59-12:00)         |[2024-07-05](https://time.lol/#2024-07-05T23:59:59-12:00)         |**[2024-07-19](https://time.lol/#2024-07-19T23:59:59-12:00)**    |

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.
##### Keep in mind the [responsibility](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR201) for violations of the [Timeline](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR103).

**Comment by Shurtu-gal** [comment]
> Might need an option to determine which application you gene

Could use the `pointOfViewOption` as was done before as well.

**Comment by jonaslagoni** [comment]
@Shurtu-gal could easily be yea 👍

@Gmin2 do you need anything from me to get started with the first step?

**Comment by Gmin2** [comment]
> @Gmin2 do you need anything from me to get started with the first step, or just in general?

going fine will ping you in slack when i need any help

**Comment by aeworxet** [comment]
@Gmin2, please provide an update to the [PR](https://github.com/asyncapi/converter-js/pull/269).

**Comment by Gmin2** [comment]
I need an extension of two weeks for this issue to be completed
@aeworxet

**Comment by aeworxet** [comment]
Upon [request of the Bounty Program Participant](https://github.com/asyncapi/converter-js/issues/233#issuecomment-2215052135) (@Gmin2), all remaining target dates of the Bounty Issue's Timeline are extended by two calendar weeks.

### Bounty Issue's Timeline Extended
|Complexity Level|Assignment date (by GitHub)|Start date (by BP rules)|End date (by BP rules)|Draft PR submission|Final PR submission|Final PR merge|
|----------------|---------------------------|------------------------|----------------------|-------------------|-------------------|--------------|
|Advanced        |2024-05-21                 |[2024-05-27](https://time.lol/#2024-05-27T00:00:00+12:00)              |**[2024-08-02](https://time.lol/#2024-08-02T23:59:59-12:00)**        |[2024-06-14](https://time.lol/#2024-06-14T23:59:59-12:00)         |[2024-07-05](https://time.lol/#2024-07-05T23:59:59-12:00)         |**[2024-08-02](https://time.lol/#2024-08-02T23:59:59-12:00)**    |

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.
##### Keep in mind the [responsibility](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR201) for violations of the [Timeline](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR103).

**Comment by aeworxet** [comment]
AsyncAPI Maintainer (@jonaslagoni) delayed response for one period of three consequent working days
https://github.com/asyncapi/converter-js/pull/269#issuecomment-2254524415
https://github.com/asyncapi/converter-js/pull/269#pullrequestreview-2209468296
so all remaining target dates of the Bounty Issue's Timeline are extended by two calendar weeks.

### Bounty Issue's Timeline Extended
|Complexity Level|Assignment date (by GitHub)|Start date (by BP rules)|End date (by BP rules)|Draft PR submission|Final PR submission|Final PR merge|
|----------------|---------------------------|------------------------|----------------------|-------------------|-------------------|--------------|
|Advanced        |2024-05-21                 |[2024-05-27](https://time.lol/#2024-05-27T00:00:00+12:00)              |**[2024-08-16](https://time.lol/#2024-08-16T23:59:59-12:00)**        |[2024-06-14](https://time.lol/#2024-06-14T23:59:59-12:00)         |[2024-07-05](https://time.lol/#2024-07-05T23:59:59-12:00)         |**[2024-08-16](https://time.lol/#2024-08-16T23:59:59-12:00)**    |

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.
##### Keep in mind the [responsibility](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR201) for violations of the [Timeline](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR103).

**Comment by jonaslagoni** [comment]
Might as well extend it two more weeks @aeworxet unless one of the other maintainers continues the review or it finishes tomorrow, as I will be AFK until the 12th.

**Comment by aeworxet** [comment]
Upon [suggestion of the AsyncAPI Maintainer](https://github.com/asyncapi/converter-js/issues/233#issuecomment-2260243319), who is responsible for the resolution of the Bounty Issue from the AsyncAPI's side (@jonaslagoni), all remaining target dates of the Bounty Issue's Timeline are extended by four calendar weeks.

### Bounty Issue's Timeline Extended
|Complexity Level|Assignment date (by GitHub)|Start date (by BP rules)|End date (by BP rules)|Draft PR submission|Final PR submission|Final PR merge|
|----------------|---------------------------|------------------------|----------------------|-------------------|-------------------|--------------|
|Advanced        |2024-05-21                 |[2024-05-27](https://time.lol/#2024-05-27T00:00:00+12:00)              |**[2024-08-30](https://time.lol/#2024-08-30T23:59:59-12:00)**        |[2024-06-14](https://time.lol/#2024-06-14T23:59:59-12:00)         |[2024-07-05](https://time.lol/#2024-07-05T23:59:59-12:00)         |**[2024-08-30](https://time.lol/#2024-08-30T23:59:59-12:00)**    |

##### Please note that the dates given represent deadlines, not specific dates, so if the goal is reached sooner, it's better.
##### Keep in mind the [responsibility](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR201) for violations of the [Timeline](https://github.com/asyncapi/community/pull/897/files#diff-25ecb20a61754c225d6511ca08d7e7c9a14b9ca5a93e89bd42331e51c9ebf26dR103).

**Comment by jonaslagoni** [comment]
Bounty issue completed

**Comment by aeworxet** [comment]
### Bounty Issue Completed 🎉

@Gmin2, please go to the [AsyncAPI page on Open Collective](https://opencollective.com/asyncapi) and submit an invoice for `USD 400.00` with the expense title `Bounty converter-js#233`, tag `bounty`, and full URL of this Bounty Issue in the description.
